//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossCam.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossCam.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Doc of Great Stuff.
        /// </summary>
        internal static string Button_GoogleDoc {
            get {
                return ResourceManager.GetString("Button.GoogleDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More Pictures.
        /// </summary>
        internal static string Button_MorePictures {
            get {
                return ResourceManager.GetString("Button.MorePictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a Review.
        /// </summary>
        internal static string Button_Review {
            get {
                return ResourceManager.GetString("Button.Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share CrossCam.
        /// </summary>
        internal static string Button_Share {
            get {
                return ResourceManager.GetString("Button.Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support the Developer.
        /// </summary>
        internal static string Button_Support {
            get {
                return ResourceManager.GetString("Button.Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a bug? Have a question? Just email .
        /// </summary>
        internal static string Footer_Span1 {
            get {
                return ResourceManager.GetString("Footer.Span1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! I love talking with users and it&apos;s the fastest way to communicate with me..
        /// </summary>
        internal static string Footer_Span3 {
            get {
                return ResourceManager.GetString("Footer.Span3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Frame up and take the first picture..
        /// </summary>
        internal static string Page_HowToUse_1 {
            get {
                return ResourceManager.GetString("Page.HowToUse.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Start anaglyph viewing the first picture with the preview that appears next to it..
        /// </summary>
        internal static string Page_HowToUse_2anaglyph {
            get {
                return ResourceManager.GetString("Page.HowToUse.2anaglyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Start cardboard viewing the first picture with the preview that appears next to it..
        /// </summary>
        internal static string Page_HowToUse_2cardboard {
            get {
                return ResourceManager.GetString("Page.HowToUse.2cardboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Start cross viewing the first picture with the preview that appears next to it..
        /// </summary>
        internal static string Page_HowToUse_2cross {
            get {
                return ResourceManager.GetString("Page.HowToUse.2cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Start parallel viewing the first picture with the preview that appears next to it..
        /// </summary>
        internal static string Page_HowToUse_2parallel {
            get {
                return ResourceManager.GetString("Page.HowToUse.2parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) Keep your phone steady in front of you and slowly move sideways in the direction CrossCam tells you to. Don&apos;t move too far - an inch or less for each foot away your target is. Also, don&apos;t turn at all, just slide sideways, or maybe even just lean..
        /// </summary>
        internal static string Page_HowToUse_3 {
            get {
                return ResourceManager.GetString("Page.HowToUse.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) Align the first picture with the preview of the second picture and take the second picture when you like what you see..
        /// </summary>
        internal static string Page_HowToUse_4 {
            get {
                return ResourceManager.GetString("Page.HowToUse.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) CrossCam will automatically align your pictures after you capture them, but it&apos;s not perfect, if you don&apos;t like how they were aligned, you can turn the automatic alignment off on the settings page. CrossCam also has plenty of manual editing options you can get to by tapping the pencil icon..
        /// </summary>
        internal static string Page_HowToUse_5 {
            get {
                return ResourceManager.GetString("Page.HowToUse.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6) Tap the check mark when you&apos;re ready to save..
        /// </summary>
        internal static string Page_HowToUse_6 {
            get {
                return ResourceManager.GetString("Page.HowToUse.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to see this again, tap the hamburger (three lines) icon on the top left of the camera screen and tap &amp;quot;Help&amp;quot;..
        /// </summary>
        internal static string Page_HowToUse_Intro {
            get {
                return ResourceManager.GetString("Page.HowToUse.Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Title_Contact {
            get {
                return ResourceManager.GetString("Title.Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string Title_Faq {
            get {
                return ResourceManager.GetString("Title.Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Title_Help {
            get {
                return ResourceManager.GetString("Title.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Use CrossCam.
        /// </summary>
        internal static string Title_HowToUse {
            get {
                return ResourceManager.GetString("Title.HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Viewing Technique.
        /// </summary>
        internal static string Title_Technique {
            get {
                return ResourceManager.GetString("Title.Technique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        internal static string Title_Tips {
            get {
                return ResourceManager.GetString("Title.Tips", resourceCulture);
            }
        }
    }
}
