<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-ios;net10.0;net10.0-android</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.22621.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net10.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType Condition="'$(TargetFramework)' != 'net10.0'">Exe</OutputType>
		<RootNamespace>CrossCam</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>CrossCam</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.kra2008.crosscam</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">12.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
		<RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
		<EnableNETAnalyzers>False</EnableNETAnalyzers>
		<AssemblyName>CrossCam</AssemblyName>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<Platforms>AnyCPU</Platforms>
		<PublishAot>False</PublishAot>
		<Trimming></Trimming>
		<Configurations>Debug;Release;Debug Without Emgu</Configurations>
		<NeutralLanguage>en-US</NeutralLanguage>
	</PropertyGroup>

	<Target Name="_OverrideFirebaseStripBitcodeFromFrameworksMasterDependsOnTargets" BeforeTargets="_ResolveNativeReferencesForFirebaseCore">
		<PropertyGroup>
			<_FirebaseStripBitcodeFromFrameworksMasterDependsOnTargets Condition="'$(OS)'=='Unix'">_OverrideFirebaseStripBitcodeFromFrameworksOnMac</_FirebaseStripBitcodeFromFrameworksMasterDependsOnTargets>
			<_FirebaseStripBitcodeFromFrameworksMasterDependsOnTargets Condition="'$(OS)'!='Unix'">_OverrideFirebaseStripBitcodeFromFrameworksOnWindows</_FirebaseStripBitcodeFromFrameworksMasterDependsOnTargets>
		</PropertyGroup>
	</Target>

	<Target Name="_OverrideFirebaseStripBitcodeFromFrameworksOnMac" />
	<Target Name="_OverrideFirebaseStripBitcodeFromFrameworksOnWindows" />

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-android|AnyCPU'">
	  <Deterministic>False</Deterministic>
	  <AndroidEnableMultiDex>True</AndroidEnableMultiDex>
	  <AndroidStoreUncompressedFileExtensions></AndroidStoreUncompressedFileExtensions>
	  <AndroidUseAapt2>True</AndroidUseAapt2>
	  <DefineConstants>$(DefineConstants);__ANDROID__;EMGU</DefineConstants>
	  <EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug Without Emgu|net10.0-android|AnyCPU'">
	  <Deterministic>False</Deterministic>
	  <AndroidEnableMultiDex>True</AndroidEnableMultiDex>
	  <AndroidStoreUncompressedFileExtensions />
	  <AndroidUseAapt2>True</AndroidUseAapt2>
	  <DefineConstants>$(DefineConstants);__ANDROID__;DEBUG</DefineConstants>
	  <EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-ios|AnyCPU'">
	  <Deterministic>False</Deterministic>
	  <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
	  <EnableSGenConc>True</EnableSGenConc>
	  <OptimizePNGs>False</OptimizePNGs>
	  <MtouchDebug>True</MtouchDebug>
	  <MtouchProfiling>True</MtouchProfiling>
	  <MtouchFloat32>True</MtouchFloat32>
	  <CodesignEntitlements>Platforms\iOS\DevEntitlements.plist</CodesignEntitlements>
	  <DefineConstants>$(DefineConstants);EMGU</DefineConstants>
	  <CodesignKey>Apple Development: Created via API (R4A4JM399F)</CodesignKey>
	  <CodesignProvision>VS: com.kra2008.crosscam Development</CodesignProvision>
	  <ProvisioningType>manual</ProvisioningType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug Without Emgu|net10.0-ios|AnyCPU'">
	  <Deterministic>False</Deterministic>
	  <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
	  <EnableSGenConc>True</EnableSGenConc>
	  <OptimizePNGs>False</OptimizePNGs>
	  <MtouchDebug>True</MtouchDebug>
	  <MtouchProfiling>True</MtouchProfiling>
	  <MtouchFloat32>True</MtouchFloat32>
	  <CodesignEntitlements>Platforms\iOS\DevEntitlements.plist</CodesignEntitlements>
	  <MtouchLink>None</MtouchLink>
	  <CodesignKey>Apple Development: Created via API (R4A4JM399F)</CodesignKey>
	  <CodesignProvision>VS: com.kra2008.crosscam Development</CodesignProvision>
      <ProvisioningType>manual</ProvisioningType>
      <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-android|AnyCPU'">
	  <EnableLLVM>True</EnableLLVM>
	  <AndroidEnableProfiledAot>False</AndroidEnableProfiledAot>
	  <AndroidUseAapt2>True</AndroidUseAapt2>
	  <AndroidStoreUncompressedFileExtensions></AndroidStoreUncompressedFileExtensions>
	  <DefineConstants>$(DefineConstants);__ANDROID__;EMGU</DefineConstants>
	  <AndroidLinkTool>r8</AndroidLinkTool>
	  <AndroidKeyStore>True</AndroidKeyStore>
	  <AndroidPackageFormat>aab</AndroidPackageFormat>
	  <AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-ios|AnyCPU'">
	  <EnableSGenConc>True</EnableSGenConc>
	  <MtouchDebug>False</MtouchDebug>
	  <BuildIpa>True</BuildIpa>
	  <AdditionalArgs>--linkskip=CrossCam --linkskip=CrossCam.iOS --linkskip=CrossCam.iOS.Extension --optimize=-remove-dynamic-registrar</AdditionalArgs>
	  <MtouchFloat32>True</MtouchFloat32>
	  <CodesignEntitlements>Platforms\iOS\ProdEntitlements.plist</CodesignEntitlements>
	  <DefineConstants>$(DefineConstants);EMGU</DefineConstants>
	  <CodesignKey>Apple Distribution: Kevin Anderson (G656MA2J22)</CodesignKey>
	  <CodesignProvision>CrossCam Distribution</CodesignProvision>
	  <ProvisioningType>manual</ProvisioningType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows10.0.19041.0|AnyCPU'">
	  <DefineConstants>$(DefineConstants);__WINDOWS__;EMGU</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows10.0.19041.0|AnyCPU'">
	  <DefineConstants>$(DefineConstants);__WINDOWS__;EMGU</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug Without Emgu|net10.0-windows10.0.19041.0|AnyCPU'">
	  <DefineConstants>$(DefineConstants);__WINDOWS__</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows10.0.22621.0|AnyCPU'">
	  <DefineConstants>$(DefineConstants);EMGU;__WINDOWS__</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug Without Emgu|net10.0-windows10.0.22621.0|AnyCPU'">
	  <DefineConstants>$(DefineConstants);__WINDOWS__</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows10.0.22621.0|AnyCPU'">
	  <DefineConstants>$(DefineConstants);__WINDOWS__</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0|AnyCPU'" />

	<PropertyGroup Condition="'$(TargetFramework)'=='net10.0-ios'">
	  <CodesignProvision>VS: com.kra2008.crosscam Development</CodesignProvision>
	  <ProvisioningType>manual</ProvisioningType>
	  <CodesignKey>Apple Development: Created via API (R4A4JM399F)</CodesignKey>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'" Include="Resources\AppIcon\appiconandroid.svg" Color="#ffffff" />
		<MauiIcon Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'" Include="Resources\AppIcon\appiconios.svg" Color="#ffffff" />
		<MauiIcon Include="Resources\AppIcon\appicon.svg" Color="#ffffff" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\**" />

		<!-- Splash Screen -->
	    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#000000" BaseSize="256,256" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <AndroidResource Remove="Resources\Fonts\**" />
	  <Compile Remove="Resources\Fonts\**" />
	  <EmbeddedResource Remove="Resources\Fonts\**" />
	  <MauiCss Remove="Resources\Fonts\**" />
	  <MauiXaml Remove="Resources\Fonts\**" />
	  <None Remove="Resources\Fonts\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Platforms\Android\Assets\AboutAssets.txt" />
	  <None Remove="Platforms\Android\google-services.json" />
	  <None Remove="Platforms\Android\proguard.cfg" />
	  <None Remove="Platforms\Windows\Resources\moiraineLeft.JPG" />
	  <None Remove="Platforms\Windows\Resources\moiraineRight.JPG" />
	  <None Remove="Platforms\Windows\Resources\moirainerightunaligned.JPG" />
	  <None Remove="Resources\AppIcon\appicon.svg" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Condition="'$(TargetFramework)' != 'net10.0'" Include="Emgu.CV.runtime.maui" Version="4.8.0.5324" />
		<PackageReference Include="Microsoft.Maui.Core" Version="9.0.70" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.70" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.70" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
		<PackageReference Include="FreshMvvm.Maui" Version="0.0.4" />
		<PackageReference Include="NewRelic.MAUI.Plugin" Version="1.1.14" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="PropertyChanged.Fody" Version="4.1.0" />
		<PackageReference Include="SkiaSharp" Version="2.88.9" />
		<PackageReference Condition="'$(TargetFramework)' != 'net10.0'" Include="SkiaSharp.Views" Version="2.88.9" />
		<PackageReference Include="SkiaSharp.Views.Maui.Core" Version="2.88.9" />
		<PackageReference Include="SkiaSharp.Views.Maui.Controls" Version="2.88.9" />
		<PackageReference Include="SkiaSharp.Views.Maui.Controls.Compatibility" Version="2.88.9" />
		<PackageReference Include="CommunityToolkit.Maui" Version="11.2.0" />
		<PackageReference Include="System.Formats.Nrbf" Version="9.0.4" />
		<PackageReference Include="System.Private.Uri" Version="4.3.2" />
		<PackageReference Include="System.Text.Json" Version="9.0.5" />
	</ItemGroup>

	<ItemGroup>
	  <ProguardConfiguration Include="Platforms\Android\proguard.cfg" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="App.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="CustomElement\BasicExpander.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="CustomElement\CameraModule.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="CustomElement\CameraSuccessOutline.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="CustomElement\ExpanderHeader.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="CustomElement\FooterLabel.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Page\CameraPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Page\ContactPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Page\DirectionsPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Page\FAQPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Page\HamburgerPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Page\HelpPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Page\PairingPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Page\SeeMorePicturesPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Page\SettingsPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Page\TechniqueHelpPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Page\TipMePage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Page\TipsPage.xaml.cs">
	    <DependentUpon>%(Filename)</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Localization\AppResources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>AppResources.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="App.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="CustomElement\BasicExpander.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="CustomElement\CameraModule.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="CustomElement\CameraSuccessOutline.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="CustomElement\ExpanderHeader.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="CustomElement\FooterLabel.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="CustomElement\iOS12WorkaroundBackButton.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="CustomElement\LazyViews\CaptureMethodSettingsView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\CameraPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\ContactPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\DirectionsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\FAQPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\HamburgerPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\HelpPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\PairingPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\SeeMorePicturesPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\SettingsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\TechniqueHelpPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\TipMePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Page\TipsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
	  <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData.Core">
	    <Version>2.10.0.1</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.GooglePlayServices.Nearby">
	    <Version>119.3.0.4</Version>
	  </PackageReference>
	  <PackageReference Include="Microsoft.Maui.Graphics.Skia" Version="9.0.40" />
	  <PackageReference Include="Xamarin.AndroidX.Annotation">
	  	<Version>1.9.1.6</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.AndroidX.AppCompat.AppCompatResources">
	  	<Version>1.7.1.1</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.AndroidX.AppCompat.Resources">
	  	<Version>1.1.0.3</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.AndroidX.Core">
	  	<Version>1.17.0</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.AndroidX.Browser">
	  	<Version>1.9.0</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen">
	  	<Version>1.0.1.17</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.8.9" />
	  <PackageReference Include="Xamarin.Google.Android.Material" Version="1.12.0.2" />
	  <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4" Version="1.0.0.34" />
	  <PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.7.1.1" />
	  <PackageReference Include="Xamarin.AndroidX.CardView" Version="1.0.0.36" />
	  <PackageReference Include="Xamarin.AndroidX.MediaRouter" Version="1.8.1.1" />
	  <PackageReference Include="Xamarin.AndroidX.VectorDrawable">
	  	<Version>1.2.0.8</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.Google.Android.Play.Review">
	  	<Version>2.0.2.2</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.GooglePlayServices.Location">
	  	<Version>121.3.0.4</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.AndroidX.Migration" Version="1.0.10" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-ios'">
		<Reference Include="Microsoft.iOS">
			<HintPath>C:\Program Files\dotnet\packs\Microsoft.iOS.Ref\17.2.8043\ref\net10.0\Microsoft.iOS.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup Condition="$(TargetFramework.StartsWith('net10.0-android')) != true">
		<Compile Remove="**\Android\**\*.cs" />
		<None Include="**\Android\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>

	<ItemGroup Condition="$(TargetFramework.StartsWith('net10.0-ios')) != true">
		<Compile Remove="**\iOS\**\*.cs" />
		<None Include="**\iOS\**\*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Platforms\Android\Resources\drawable-hdpi\" />
	  <Folder Include="Platforms\Android\Resources\drawable-xhdpi\" />
	  <Folder Include="Platforms\Android\Resources\drawable-xxxhdpi\" />
	  <Folder Include="Platforms\Android\Resources\drawable\" />
	  <Folder Include="Platforms\Android\Resources\drawable-hdpi\" />
	  <Folder Include="Platforms\Android\Resources\drawable-xhdpi\" />
	  <Folder Include="Platforms\Android\Resources\drawable-xxxhdpi\" />
	  <Folder Include="Platforms\Android\Resources\layout\" />
	  <Folder Include="Platforms\iOS\Resources\" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Platforms\Windows\Resources\moiraineleft.JPG" />
	  <EmbeddedResource Include="Platforms\Windows\Resources\moiraineright.JPG" />
	  <EmbeddedResource Include="Platforms\Windows\Resources\moirainerightunaligned.JPG" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="FodyWeavers.xsd" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="Microsoft.Maui">
	    <HintPath>..\..\..\NuGet\global-packages\microsoft.maui.core\8.0.6\lib\net10.0-windows10.0.19041\Microsoft.Maui.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\Localization\AppResources.en.resx">
	    <Generator></Generator>
	  </EmbeddedResource>
	  <EmbeddedResource Update="Resources\Localization\AppResources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>
